In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/frankData612/data_612/master/stock_data/stocks_yahoo.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
df.head(10)

   no         date  ... Dividend Yield  1Y target est
0   1  Nov 21 2019  ...      N/A (N/A)        1487.52
1   2  Nov 21 2019  ...      N/A (N/A)        1459.33
2   3  Nov 21 2019  ...   6.48 (4.86%)         148.30
3   4  Nov 21 2019  ...   2.04 (1.36%)         160.16
4   5  Nov 21 2019  ...   3.08 (1.16%)         257.21
5   6  Nov 21 2019  ...      N/A (N/A)        2183.86
6   7  Nov 21 2019  ...      N/A (N/A)            NaN
7   8  Nov 21 2019  ...   0.96 (1.70%)          56.27
8   9  Nov 21 2019  ...      N/A (N/A)          66.40
9  10  Nov 21 2019  ...   3.60 (2.78%)         123.71

[10 rows x 19 columns]

In [10]:
df.tail(10)

          no         date  ... Dividend Yield  1Y target est
67895  67896  Apr 28 2020  ...      N/A (N/A)         137.25
67896  67897  Apr 28 2020  ...   0.64 (2.95%)          24.00
67897  67898  Apr 28 2020  ...   0.32 (1.21%)          34.13
67898  67899  Apr 28 2020  ...      N/A (N/A)          28.00
67899  67900  Apr 28 2020  ...      N/A (N/A)          66.75
67900  67901  Apr 28 2020  ...      N/A (N/A)          12.83
67901  67902  Apr 28 2020  ...   0.44 (1.49%)          33.33
67902  67903  Apr 28 2020  ...      N/A (N/A)          11.50
67903  67904  Apr 28 2020  ...      N/A (N/A)          67.67
67904  67905  Apr 28 2020  ...      N/A (N/A)          67.62

[10 rows x 19 columns]

In [11]:
df.columns

Index(['no', 'date', 'company_name', 'price_at_close', 'price_change',
       'price_after_hours', 'previous_close', 'today opened', 'price range',
       '52 week range', 'volume', 'average volume', 'market cap',
       'beta (3Y Monthly)', 'PE Ratio', 'EPS', 'earnings date',
       'Dividend Yield', '1Y target est'],
      dtype='object')

In [13]:
df.dtypes

no                     int64
date                  object
company_name          object
price_at_close       float64
price_change          object
price_after_hours    float64
previous_close       float64
today opened         float64
price range           object
52 week range         object
volume                object
average volume       float64
market cap            object
beta (3Y Monthly)    float64
PE Ratio             float64
EPS                  float64
earnings date         object
Dividend Yield        object
1Y target est        float64
dtype: object

In [14]:
df.shape

(67905, 19)

In [16]:
df.groupby(['no', 'company_name'])[['today opened', 'price_at_close', 'price_after_hours']].mean()

                                                         today opened  ...  price_after_hours
no    company_name                                                     ...
1     GOOG - Alphabet Inc.                                    1301.48  ...            1301.35
2     GOOGL - Alphabet Inc.                                   1299.25  ...            1300.14
3     IBM - International Business Machines Corporation        133.40  ...             133.84
4     MSFT - Microsoft Corporation                             149.40  ...             149.48
5     AAPL - Apple Inc.                                        263.69  ...             262.01
...                                                               ...  ...                ...
67901 FLEX - Flex Ltd.                                           9.11  ...               9.11
67902 MEI - Methode Electronics, Inc.                           30.19  ...              29.84
67903 IEC - IEC Electronics Corp.                                7.10  ...               7.01
67904 MGLN - Magellan Health, Inc.                              54.74  ...              55.11
67905 ZS - Zscaler, Inc.                                        71.00  ...              66.72

[67905 rows x 3 columns]